---
- name: USER on AIX
  hosts: "{{host_name}}"
  gather_facts: false
  vars:
    host_name: snaptest
    user_name: aixguest
    password_val: Password
    attribute_home: /home/test/aixguest

  tasks:
    - name: Reset Data
      ibm.power_aix.snap:
        live_kernel: false
        compress: false
        hacmp: false
        reset: true
    - name: ALL Data
      ibm.power_aix.snap:
        live_kernel: false
        all_info: true
    - name: Collects dump
      ibm.power_aix.snap:
        live_kernel: false
        compress: false
        hacmp: false
        reset: false
        collects_dump: true
    - name: Compress Data
      ibm.power_aix.snap:
        live_kernel: false
        compress: true
        hacmp: false
        reset: false
    - name: HACMP  Data collection
      ibm.power_aix.snap:
        live_kernel: false
        compress: false
        hacmp: true
    - name: Compress Data
      ibm.power_aix.snap:
        live_kernel: false
        compress: false
        file_system_info: true
    - name: Live kernal data
      ibm.power_aix.snap:
        live_kernel: true
        compress: false
        file_system_info: false
    - name: Collects dump data
      ibm.power_aix.snap:
        collects_dump: true
        compress: false
        file_system_info: false
    - name: Installation software data
      ibm.power_aix.snap:
        installation_info: true
        compress: false
        file_system_info: false
    - name: Kernel related info
      ibm.power_aix.snap:
        kernel_info: true
        compress: false
        file_system_info: false
    - name: Security info data
      ibm.power_aix.snap:
        security_info: true
        general_info: true
        compress: false
        file_system_info: false
    - name: Workload manager info
      ibm.power_aix.snap:
        workload_manager_info: true
        compress: false
        file_system_info: false
    - name: Hardware info data
      ibm.power_aix.snap:
        hardware_info: true
        compress: false
        file_system_info: false
