---
name: run ibm.power_aix collection sanity tests

# run sanity test during pull request to dev-collection
on:
  pull_request:
    branches: [dev-collection]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ########################################################################
  # sanity test
  # - makes sure that the collection passes the ansible sanity tests
  ########################################################################
  sanity-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ansible_collections/ibm/power_aix
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    name: running sanity tests with python ${{ matrix.python-version }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          path: ansible_collections/ibm/power_aix

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install sanity test requirements
        run: |
          make install-sanity-test-requirements

      - name: run sanity test with python ${{ matrix.python-version }}
        run: |
          make sanity-test PYTHON_VERSION=${{ matrix.python-version }}
